spring.application.name=business.management
spring.config.import=optional:file:env.properties
server.servlet.context-path=/api/gym-management/v1
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
server.port=9092
spring.datasource.driver-class-name=org.postgresql.Driver
app.security.aes-key=${SECRET_KEY}